
import java.io.FileWriter;
import java.io.File; 
import java.io.IOException;
import java.util.*;
import java.io.*;
import java.io.FileNotFoundException;  
import java.util.Scanner; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class projform extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public projform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        empname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empsalary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        empovertime = new javax.swing.JTextField();
        empposition = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        leftarea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        findbtn = new javax.swing.JButton();
        avgbtn = new javax.swing.JButton();
        finalslybtn = new javax.swing.JButton();
        bestempbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rightarea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        empnumber = new javax.swing.JTextField();
        createbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add new employee");

        jLabel2.setText("Employee name");

        empname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empnameActionPerformed(evt);
            }
        });

        jLabel3.setText("Salary");

        empsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empsalaryActionPerformed(evt);
            }
        });

        jLabel4.setText("Position");

        empovertime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empovertimeActionPerformed(evt);
            }
        });

        empposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principal", "coordinator", "teacher", "assistant" }));

        jLabel5.setText("Overtime");

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        leftarea.setColumns(20);
        leftarea.setRows(5);
        jScrollPane1.setViewportView(leftarea);

        jLabel6.setText("Search");

        findbtn.setText("Find assistant");
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });

        avgbtn.setText("Average assistant salary");
        avgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgbtnActionPerformed(evt);
            }
        });

        finalslybtn.setText("Final salary");
        finalslybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalslybtnActionPerformed(evt);
            }
        });

        bestempbtn.setText("Best employee");
        bestempbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestempbtnActionPerformed(evt);
            }
        });

        rightarea.setColumns(20);
        rightarea.setRows(5);
        jScrollPane2.setViewportView(rightarea);

        jLabel7.setText("Employee number");

        empnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empnumberActionPerformed(evt);
            }
        });

        createbtn.setText("Create file");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(empovertime, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(savebtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(31, 31, 31)))
                            .addGap(32, 32, 32)
                            .addComponent(viewbtn))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(empposition, 0, 85, Short.MAX_VALUE)
                                    .addComponent(empsalary)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(empname, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(empnumber))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bestempbtn)
                                    .addComponent(finalslybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createbtn)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(avgbtn)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(findbtn)
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(empnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(findbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addComponent(avgbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empposition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finalslybtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empovertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(bestempbtn))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savebtn)
                            .addComponent(viewbtn)
                            .addComponent(createbtn))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private final static String newline = "\n";
    private void empnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empnameActionPerformed

    private void empsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empsalaryActionPerformed

    private void empovertimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empovertimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empovertimeActionPerformed

    private void finalslybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalslybtnActionPerformed
        // TODO add your handling code here:
        rightarea.setText("");
       /* double newsalary = 0;
        for (int k = 0; k<a;k++){
            newsalary = salaries[k] + (15 * overtimes[k]);
            rightarea.append("Final salary for " + names[k] + " is " + newsalary + newline)
        }*/
       String[] splitup;  
       double finalsalary;
       try {
                FileReader fr = new FileReader("employeeform.txt");
                Scanner sc = new Scanner(fr);
                while (sc.hasNextLine()){
                    String s = sc.nextLine();
                    splitup = s.split(", ");
                   /* for (int i = 0; i<4;i++){
                        System.out.println(splitup[i]);
                    }*/
                   finalsalary = Double.parseDouble(splitup[2]) + (15 * (Integer.parseInt(splitup[3])));
                    rightarea.append("The final salary for " + splitup[0] + " is " + finalsalary + newline);
                    }
                
                   
                       
                       /* isAssistant = elements[1];
                        isAssistant = isAssistant.trim();
                        if ("Assistant".equals(isAssistant)) {

                            rightarea.append(elements[0] + " is an Assistant" + "\n");*/
                        
                   
               
            } catch (IOException e) {
                rightarea.setText("ERROR");
            }
      
    }//GEN-LAST:event_finalslybtnActionPerformed

    private void avgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgbtnActionPerformed
        // TODO add your handling code here:
         /*rightarea.setText("");
         double totalsalary = 0;
         int totalnum = 0;
        for (int j = 0; j<a;j++){
            if (positions[j] == 4){
                totalsalary = totalsalary + salaries[j];
                totalnum = totalnum + 1;
            }
        }
        double avg = totalsalary/totalnum;
        rightarea.append("Avg assistant salary = " + avg + newline );*/
         String[] splitup;
         int totalnum = 0;  
         double totalsalary = 0;

            rightarea.setText("Average Assistant salary: " + newline);
            try {
                FileReader fr = new FileReader("employeeform.txt");
                Scanner sc = new Scanner(fr);
                while (sc.hasNextLine()){
                    String s = sc.nextLine();
                    splitup = s.split(", ");
                   /* for (int i = 0; i<4;i++){
                        System.out.println(splitup[i]);
                    }*/
                    if ("assistant".equals(splitup[1])){
                        totalsalary = totalsalary + Double.parseDouble(splitup[2]);
                        totalnum = totalnum + 1;
                    }
                }
                   
                       
                       /* isAssistant = elements[1];
                        isAssistant = isAssistant.trim();
                        if ("Assistant".equals(isAssistant)) {

                            rightarea.append(elements[0] + " is an Assistant" + "\n");*/
                        
                   
               
            } catch (IOException e) {
                rightarea.setText("ERROR");
            }
            Double avg = totalsalary/totalnum;
               rightarea.append(avg + " AED"); 
    }//GEN-LAST:event_avgbtnActionPerformed
String[] names;
int[] positions;
double[] salaries;
int[] overtimes;
int a = 0;

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        
      /*  int num = Integer.parseInt(empnumber.getText());
        while (empnumber.getText()!=""){
            String name = empname.getText();
            names[num-1] = name;
            int position = empposition.getSelectedIndex();
            positions[num-1] = position;
            double salary = Double.parseDouble(empsalary.getText());
            salaries[num-1] = salary;
            int overtime = Integer.parseInt(empovertime.getText());
            overtimes[num-1] = overtime;
            a = a + 1;
        }*/
         String name = empname.getText();
         Object position = empposition.getSelectedItem();
         
         double salary = Double.parseDouble(empsalary.getText());
         int overtime = Integer.parseInt(empovertime.getText());
       
          try {
            FileWriter f = new FileWriter("employeeform.txt", true);
            f.write(name + ", " + position + ", " + salary + ", " + overtime + ", " + newline);
            f.close();
            leftarea.setText("Saved to the file");
        } catch (Exception e) {
            leftarea.setText("ERROR");
        }
       
     /* int positiont = empposition.getSelectedIndex();
       positions = Arrays.copyOf(positions,positions.length + 1);
      positions[positions.length - 1] = positiont;
       
       String namet = empname.getText();
       names = Arrays.copyOf(names,names.length + 1);
      names[names.length - 1] = namet;
      
      double salaryt = Double.parseDouble(empsalary.getText());
      salaries = Arrays.copyOf(salaries,salaries.length + 1);
      salaries[salaries.length - 1] = salaryt;
      
      int overtimet = Integer.parseInt(empovertime.getText());
      overtimes = Arrays.copyOf(overtimes, overtimes.length + 1);
      overtimes[overtimes.length - 1] = overtimet;
      */
      
      
      
      
        empnumber.setText(null);
        empname.setText(null);
        empsalary.setText(null);
        empovertime.setText(null);
        
    }//GEN-LAST:event_savebtnActionPerformed
       
    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed
        // TODO add your handling code here:
       
       /* for (int i = 0; i<a;i++){
            if (positions[i] == 4){
                rightarea.append(names[i] + ", " + salaries[i] + " AED , " + overtimes[i] + " hours" + newline);
            }
        }*/
         String[] splitup;
            

            rightarea.setText("Assistants:" + newline);
            try {
                FileReader fr = new FileReader("employeeform.txt");
                Scanner sc = new Scanner(fr);
                while (sc.hasNextLine()){
                    String s = sc.nextLine();
                    splitup = s.split(", ");
                   /* for (int i = 0; i<4;i++){
                        System.out.println(splitup[i]);
                    }*/
                    if ("assistant".equals(splitup[1])){
                        rightarea.append(splitup[0] + newline);
                    }
                }
                    
                       
                       /* isAssistant = elements[1];
                        isAssistant = isAssistant.trim();
                        if ("Assistant".equals(isAssistant)) {

                            rightarea.append(elements[0] + " is an Assistant" + "\n");*/
                        
                   
               
            } catch (IOException e) {
                rightarea.setText("ERROR");
            }
        
        
    }//GEN-LAST:event_findbtnActionPerformed

    private void bestempbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestempbtnActionPerformed
        // TODO add your handling code here:
        /*rightarea.setText("");
        int maxnum = 0;
        for (int l = 1; l<a;l++){
            if (overtimes[l] > overtimes[maxnum]){
                maxnum = l;
            }
        }
        rightarea.append("Best employee = " + names[maxnum] + newline);
        double bestempsalary = (1.15 * (salaries[maxnum]));
        rightarea.append("Best employee salary" + bestempsalary + newline);*/
        String[] splitup;  
       String bestemp = "";
       double bestsalary = 0;
       int besthours = 0;
       try {
                FileReader fr = new FileReader("employeeform.txt");
                Scanner sc = new Scanner(fr);
                while (sc.hasNextLine()){
                    String s = sc.nextLine();
                    splitup = s.split(", ");
                   /* for (int i = 0; i<4;i++){
                        System.out.println(splitup[i]);
                    }*/
                   if (Integer.parseInt(splitup[3])>besthours){
                       besthours = Integer.parseInt(splitup[3]);
                       bestsalary = Double.parseDouble(splitup[2]);
                       bestemp = splitup[0];
                       bestsalary = 1.15 * bestsalary;
                   }
                    }
                
                   
                    rightarea.append("The best employee is " + bestemp + " with overtime hours of " + besthours + " hours and a new salary of " + bestsalary + " AED");   
                       /* isAssistant = elements[1];
                        isAssistant = isAssistant.trim();
                        if ("Assistant".equals(isAssistant)) {

                            rightarea.append(elements[0] + " is an Assistant" + "\n");*/
                        
                   
               
            } catch (IOException e) {
                rightarea.setText("ERROR");
            }
      
       
    }//GEN-LAST:event_bestempbtnActionPerformed

    private void empnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empnumberActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
         leftarea.setText("");
        /*try {
            FileReader fr = new FileReader("employeeform.txt");
            BufferedReader b = new BufferedReader(fr);
            String line = b.readLine();
            while (line != null) {
                leftarea.append(line + newline);
                line = b.readLine();
            }
            fr.close();
        } catch (Exception e) {
            leftarea.setText("An error occured");
        }*/
 try {
      FileReader fr = new FileReader("employeeform.txt");
      BufferedReader b = new BufferedReader(fr);
      File f = new File("employeeform.txt");
      Scanner sc = new Scanner(f);
      while (sc.hasNextLine()) {
        String s = sc.nextLine();
        leftarea.append(s + newline);
      }
      sc.close();
    } catch (FileNotFoundException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
    
    }//GEN-LAST:event_viewbtnActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
   /* try {
        File myObj = new File("employeeform.txt");
             if (myObj.createNewFile()) {
                   leftarea.setText("File created: " + myObj.getName()+newline);
            } else {
             leftarea.setText("File already exists.");
         }
          } catch (IOException e) {
              leftarea.setText("An error occurred.");
         e.printStackTrace();
    }*/
    }//GEN-LAST:event_createbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avgbtn;
    private javax.swing.JButton bestempbtn;
    private javax.swing.JButton createbtn;
    private javax.swing.JTextField empname;
    private javax.swing.JTextField empnumber;
    private javax.swing.JTextField empovertime;
    private javax.swing.JComboBox<String> empposition;
    private javax.swing.JTextField empsalary;
    private javax.swing.JButton finalslybtn;
    private javax.swing.JButton findbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea leftarea;
    private javax.swing.JTextArea rightarea;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
